version: '3.8'
services:

  postgres:
    image: postgres:15.2
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pleo
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: antaeus
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "pleo", "-d", "antaeus" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:417.0.0-emulators
    container_name: pubsub
    ports:
      - "8085:8085"
    command: >
      bash -c "
        gcloud beta emulators pubsub start --host-port 0.0.0.0:8085 &
        sleep 8 &&
        curl -X PUT http://localhost:8085/v1/projects/pleo/topics/billing_trigger &&
        curl -X PUT -H 'Content-Type: application/json' -d '{\"topic\": \"projects/pleo/topics/billing_trigger\"}' http://localhost:8085/v1/projects/pleo/subscriptions/antaeus_svc-billing_trigger &&
        curl -X PUT http://localhost:8085/v1/projects/pleo/topics/notifications &&
        curl -X PUT http://localhost:8085/v1/projects/pleo/topics/invoices &&
        curl -X PUT -H 'Content-Type: application/json' -d '{\"topic\": \"projects/pleo/topics/invoices\", \"enableMessageOrdering\": true}' http://localhost:8085/v1/projects/pleo/subscriptions/antaeus_svc-invoices &&
        tail -f /dev/null
      "

  scheduler:
    build: ./pleo-antaeus-scheduler
    image: scheduler
    container_name: scheduler
  
  pleo-antaeus:
    build: .
    image: pleo-antaeus
    container_name: pleo-antaeus
    ports:
      - "8080:8080"
    volumes:
      - antaeus-build-cache:/root/.gradle
    environment:
      POSTGRES_HOST: postgres:5432
      PUBSUB_EMULATOR_HOST: pubsub:8085
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  antaeus-build-cache:
  postgres-data: